config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Ibercivis/TwitterDataMining:
      branch: master
      repo: https://github.com/Ibercivis/TwitterDataMining
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Ibercivis/TwitterDataMining git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-aqua-toucan.sh
        container: qc.acc_sleepy-malachite-snake
  QC.Doc:
    repos:
      github.com/Ibercivis/TwitterDataMining find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-bistre-eagle.sh
        container: qc.doc_tacky-vermilion-frise
      github.com/Ibercivis/TwitterDataMining git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-olivine-gerbil.sh
        container: qc.doc_homely-chestnut-neanderthal
      github.com/Ibercivis/TwitterDataMining restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ultramarine-saola.sh
        container: qc.doc_snappy-alizarin-macaque
  QC.Lic:
    repos:
      github.com/Ibercivis/TwitterDataMining licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-peach-chinchilla.sh
        container: qc.lic_woolly-maroon-turtle
  QC.Sec:
    repos:
      github.com/Ibercivis/TwitterDataMining bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-lilac-turkey.sh
        container: qc.sec_dorky-ivory-ocelot
  QC.Sty:
    repos:
      github.com/Ibercivis/TwitterDataMining flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-crimson-dragon.sh
        container: qc.sty_crabby-viridian-stoat
  QC.Ver:
    repos:
      github.com/Ibercivis/TwitterDataMining get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-smalt-stingray.sh
        container: qc.ver_pretty-fuchsia-mist
timeout: 5400
